# ComfyUI自动化系统配置文件

comfyui:
  # ComfyUI安装路径
  path: "D:/LM/ComfyUI"
  
  # API服务地址
  api_url: "http://127.0.0.1:8188"
  
  # 启动模式: auto(自动启动) | manual(手动启动) | check_only(仅检查)
  startup_mode: "auto"
  
  # 启动超时时间(秒)
  startup_timeout: 120

generation:
  # 默认图像分辨率 [宽, 高]
  default_resolution: [1024, 1024]
  
  # 默认采样步数
  default_steps: 20
  
  # 默认引导强度
  default_guidance: 3.5
  
  # 批次大小
  batch_size: 1
  
  # 最大并发任务数
  max_concurrent_tasks: 1

output:
  # 输出基础目录
  base_directory: "./output"
  
  # 文件组织方式: date(按日期) | subject(按主题) | style(按风格)
  organize_by: "date"
  
  # 是否保存元数据
  save_metadata: true
  
  # 是否生成HTML画廊
  generate_gallery: true