# FLUX工作流配置
workflow_info:
  name: "txt2img"
  version: "1.1.0"
  description: "FLUX分离加载器工作流"
  author: "ComfyUI Automation"
  created_date: "2025-09-09"
  
# 工作流文件路径
workflow_file: "flux_workflow.json"

# 默认参数
default_params:
  # 图像尺寸
  width: 1024
  height: 1024
  batch_size: 1
  
  # 采样参数
  steps: 20
  cfg: 7.0
  sampler_name: "euler"
  scheduler: "simple"
  denoise: 1.0
  
  # 种子设置
  seed: -1
  
  # 输出设置
  filename_prefix: "flux_txt2img"
  save_format: "png"

# 参数映射
parameter_mapping:
  # 提示词相关
  prompt:
    node_id: "2"
    input_name: "text"
    description: "正面提示词"
    required: true
    
  negative_prompt:
    node_id: "3" 
    input_name: "text"
    description: "负面提示词"
    required: false
    default: ""
    
  # 图像尺寸
  width:
    node_id: "1"
    input_name: "width"
    description: "图像宽度"
    type: "integer"
    min: 64
    max: 2048
    step: 64
    
  height:
    node_id: "1"
    input_name: "height"
    description: "图像高度"
    type: "integer"
    min: 64
    max: 2048
    step: 64
    
  batch_size:
    node_id: "1"
    input_name: "batch_size"
    description: "批次大小"
    type: "integer"
    min: 1
    max: 10
    
  # 采样参数
  steps:
    node_id: "7"
    input_name: "steps"
    description: "采样步数"
    type: "integer"
    min: 1
    max: 50
    
  cfg:
    node_id: "7"
    input_name: "cfg"
    description: "CFG Scale"
    type: "float"
    min: 1.0
    max: 20.0
    
  sampler_name:
    node_id: "7"
    input_name: "sampler_name"
    description: "采样器名称"
    type: "string"
    
  scheduler:
    node_id: "7"
    input_name: "scheduler"
    description: "调度器"
    type: "string"
    
  # 种子
  seed:
    node_id: "7"
    input_name: "seed"
    description: "随机种子"
    type: "integer"
    min: 0
    max: 2147483647
    
  # 降噪强度
  denoise:
    node_id: "7"
    input_name: "denoise"
    description: "降噪强度"
    type: "float"
    min: 0.0
    max: 1.0
    default: 1.0
    
  # 输出文件名
  filename_prefix:
    node_id: "9"
    input_name: "filename_prefix"
    description: "输出文件名前缀"
    type: "string"

# 节点验证规则
node_validation:
  required_nodes:
    - id: "1"
      class_type: "EmptyLatentImage"
      description: "空白潜在图像节点"
      
    - id: "2"
      class_type: "CLIPTextEncode"
      description: "正面提示词编码节点"
      
    - id: "4"
      class_type: "DualCLIPLoader"
      description: "FLUX CLIP加载器"
      
    - id: "5"
      class_type: "UNETLoader"
      description: "FLUX模型加载器"
      
    - id: "6" 
      class_type: "VAELoader"
      description: "VAE加载器"
      
    - id: "7"
      class_type: "KSampler"
      description: "K采样器节点"
      
    - id: "9"
      class_type: "SaveImage"
      description: "图像保存节点"

# 输出配置
output_config:
  output_directory: "output/txt2img"
  filename_template: "{task_id}_{timestamp}_{prompt_hash}"
  supported_formats: ["png", "jpg", "jpeg"]
  save_metadata: true
  metadata_format: "json"

# 性能配置
performance:
  task_timeout: 600
  max_retries: 3
  memory_limit_mb: 8192
  max_concurrent_tasks: 1

# 兼容性检查
compatibility:
  comfyui_version_min: "0.1.0"
  required_custom_nodes: []